apiVersion: apps/v1
kind: Deployment
metadata:
  name: planeteclipse-org
  namespace: foundation-internal-webdev-apps
spec:
  selector:
    matchLabels:
      app: planeteclipse-org
      environment: production
  replicas: 2
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: planeteclipse-org
        environment: production
    spec:
      containers:
      - name: nginx
        image: eclipsefdn/nginx:stable-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: planet-www
          mountPath: /usr/share/nginx/html/planet
        resources:
          limits:
            cpu: '2'
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /planet
            port: 8080
          initialDelaySeconds: 900
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /planet
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 5
      - name: planet-venus
        image: eclipsefdn/planeteclipse.org:latest
        volumeMounts:
        - name: planet-www
          mountPath: /var/planet/www
        - name: planet-cache
          mountPath: /var/planet/cache
        resources:
          limits:
            cpu: '2'
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 512Mi
      volumes:
      - name: planet-www
        emptyDir: {}
      - name: planet-cache
        emptyDir: {}
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: planeteclipse-org
  namespace: foundation-internal-webdev-apps
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: planeteclipse-org
    environment: production
---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  name: planeteclipse-org
  namespace: foundation-internal-webdev-apps
  annotations:
    haproxy.router.openshift.io/timeout: 20s
spec:
  host: "planeteclipse.org"
  path: "/planet"
  port:
    targetPort: "http"
  tls:
    insecureEdgeTerminationPolicy: "Redirect"
    termination: "edge"
  to:
    kind: "Service"
    name: planeteclipse-org
    weight: 100
